version: "3"
services:
  backend:
    build: ./backend
    image: loockhin/backend:1.0
    ports:
      - 3000:3000

  mongo:
    build: ./database
    container_name: mongo
    image: my_mongo:1.0
    environment:
      MONGO_INITDB_DATABASE: mongo-test
    # volumes:
    #   - data:/data/db
    #   - configdb:/data/configdb

volumes:
  data:
  configdb: 